In [1]:
#Menggunakan Numpy

import numpy as np

list1 = [0,1,2,3,4]
array1d = np.array(list1)
array1d

array([0, 1, 2, 3, 4])

In [2]:
#Tipe Data
type(array1d)

numpy.ndarray

In [3]:
#Menjumlahkan element array:
array1d + 2

array([2, 3, 4, 5, 6])

In [4]:
#Membuat array 2 dimensi
list2 = [[0,1,2.1,3],[2,4,6,8.8],[3,6,9,12]]
array2d = np.array(list2)
array2d

array([[ 0,  1,  2,  3],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [5]:
#Mengatur Jenis Data : Float / Int
array2d.astype('int')


array([[ 0,  1,  2,  3],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12]])

In [9]:
#Mengambil element tertentu pada array
data1 = array2d[:1, :1]
data2 = array2d[:1, :2]
data1
data2

array([[0, 1]])

In [12]:
#Operasi Mean / Min / Max
array2d.mean()
array2d.max()
array2d.min()


0

In [16]:
#Reshape and Flattening
#Reshape = Mengubah Dimensi Array
#Flattening = Mengubah Array Menjadi 1 Dimensi

array2d_new_dimension = array2d.reshape(4,3)
array2d_new_dimension

array([[ 0,  1,  2],
       [ 3,  2,  4],
       [ 6,  8,  3],
       [ 6,  9, 12]])

In [17]:
#Flattening
array2d.flatten()

array([ 0,  1,  2,  3,  2,  4,  6,  8,  3,  6,  9, 12])

In [24]:
#Membuat Array yang datanya terisi secara otomatis
np.arange(10)
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
#Membuat Array dengan jumlah pasti, dengan angka antara 1 dan 50
#Sejumlah num angka
np.linspace(start=20, stop=30, num=10, dtype=int)


array([20, 21, 22, 23, 24, 25, 26, 27, 28, 30])

In [28]:
#Membuat Matriks yang isinya 0 atau 1
np.zeros([3,4])
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
#Membuat Array yang isinya bilangan acak
np.random.rand(3,4)

#Membuat array bilangan acak dari n sampai n-1
np.random.randint(3,100, size=[3,4])


array([[34, 29, 59,  9],
       [22,  5,  8, 49],
       [42,  5, 32, 13]])

In [31]:
#Memilih 10 data acak dari 2 pilihan
np.random.choice(['Pria','Wanita'], size=10)



array(['Pria', 'Pria', 'Pria', 'Pria', 'Pria', 'Pria', 'Pria', 'Wanita',
       'Wanita', 'Wanita'], dtype='<U6')